---
title: "BA"
author: "Ji Won"
date: "5/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(maps)
library(maptools)
library(mgcv)
library(extRemes)
library(ROCR)
library(xgboost)
library(gbm)
```


```{r cars}
load("~/Desktop/Project/data_train.RData")

data_train_DF<- data_train_DF %>%
  mutate(wind = sqrt(clim1^2 + clim2^2)) %>%
  dplyr::rename(dew_temp = clim3,
         temp = clim4,
         pot_evap = clim5,
         solar_rad = clim6,
         thermal_rad = clim7,
         pressure = clim8,
         evap = clim9,
         precip = clim10) %>%
  subset(select = -c(clim1, clim2) )

dat_scaled <- as.data.frame(scale(data_train_DF[,c(8:36)]))
dat_scaled <- cbind(data_train_DF[,c(1:7)], dat_scaled)

train_data <- filter(dat_scaled, year == 1995| year== 2005 | year ==2015)
test <- filter(dat_scaled, year == 1997 | year == 2007)

train_data<- train_data%>%
  group_by(lon, lat, month)%>%
  mutate(mean_monthly_BA= mean(BA))

train_data<- train_data%>%
  group_by(lon, lat, month)%>%
  mutate(mean_monthly_CNT= mean(CNT))

for (m in 3:9){
  for (L in seq(-124.75, -66.75, 0.5)){
    for (l in seq(25.25, 49.25, 0.5)){
      test$mean_monthly_BA[test$lon==L & test$lat==l & test$month==m] <- 
        train_data$mean_monthly_BA[train_data$lon==L & train_data$lat==l & train_data$month==m][1]
      test$mean_monthly_CNT[test$lon==L & test$lat==l & test$month==m] <- 
        train_data$mean_monthly_CNT[train_data$lon==L & train_data$lat==l & train_data$month==m][1]
    }
  }
} 


rm(L, l, m, data_train_DF)
```




```{r}
m_gbm_all <- gbm(log(BA+1) ~ .-CNT, data = train_data, distribution = "gaussian", interaction.depth = 6, n.trees=1000, n.minobsinnode = 2, shrinkage = 0.001)

p_gbm_all <- predict_ba_prob_gaussian_gbm1(m_gbm_all, test)
s_gbm <- get_score_ba(p_gbm_all, test$BA, u_ba, weights_ba)
s_gbm
```

```{r}
m_gbm1 <- gbm(log(BA+1) ~ .-CNT-mean_monthly_BA, data = train_data, distribution = "gaussian", interaction.depth = 6, n.trees=1000, n.minobsinnode = 2, shrinkage = 0.001)

p_gbm1 <- predict_ba_prob_gaussian_gbm1(m_gbm1, test)
s_gbm1 <- get_score_ba(p_gbm1, test$BA, u_ba, weights_ba)
s_gbm1
```


```{r}
m_gbm2 <- gbm(log(BA+1) ~ .-CNT-mean_monthly_BA, data = train_data, distribution = "gaussian", interaction.depth = 6, n.trees=1000, n.minobsinnode = 2, shrinkage = 0.01)

p_gbm2 <- predict_ba_prob_gaussian_gbm1(m_gbm2, test)
s_gbm2 <- get_score_ba(p_gbm2, test$BA, u_ba, weights_ba)
s_gbm2
```

```{r}
m_gbm3 <- gbm(log(BA+1) ~ .-CNT-mean_monthly_BA, data = train_data, distribution = "gaussian", interaction.depth = 6, n.trees=1000, n.minobsinnode = 10, shrinkage = 0.01)

p_gbm3 <- predict_ba_prob_gaussian_gbm1(m_gbm3, test)
s_gbm3 <- get_score_ba(p_gbm3, test$BA, u_ba, weights_ba)
s_gbm3
```

```{r}
m_gbm4 <- gbm(log(BA+1) ~ .-CNT-mean_monthly_BA-overthreshold, data = train_data, distribution = "gaussian", interaction.depth = 5, n.trees=1000, n.minobsinnode = 10, shrinkage = 0.1)

p_gbm4 <- predict_ba_prob_gaussian_gbm1(m_gbm4, test)
s_gbm4 <- get_score_ba(p_gbm4, test$BA, u_ba, weights_ba)
s_gbm4


```


```{r}
m_gbm5 <- gbm(log(BA+1) ~ .-CNT-mean_monthly_CNT-mean_monthly_BA, data = train_data, distribution = "gaussian", interaction.depth = 6, n.trees=1000, n.minobsinnode = 10, shrinkage = 0.1)

p_gbm5 <- predict_ba_prob_gaussian_gbm1(m_gbm5, test)
s_gbm5 <- get_score_ba(p_gbm5, test$BA, u_ba, weights_ba)
s_gbm5
```


```{r}
m_gbm6 <- gbm(log(BA+1) ~ .-CNT-mean_monthly_CNT, data = train_data, distribution = "gaussian", interaction.depth = 6, n.trees=1000, n.minobsinnode = 10, shrinkage = 0.1)

p_gbm6 <- predict_ba_prob_gaussian_gbm1(m_gbm6, test)
s_gbm6 <- get_score_ba(p_gbm6, test$BA, u_ba, weights_ba)
s_gbm6
```

# including CNT
```{r}
m_gbm7 <- gbm(log(BA+1) ~., data = train_data, distribution = "gaussian", interaction.depth = 6, n.trees=1000, n.minobsinnode = 10, shrinkage = 0.1)

p_gbm7 <- predict_ba_prob_gaussian_gbm1(m_gbm7, test)
s_gbm7 <- get_score_ba(p_gbm7, test$BA, u_ba, weights_ba)
s_gbm7
```

```{r}
m_gbm8 <- gbm(log(BA+1) ~.-mean_monthly_BA-overthreshold, data = train_data, distribution = "gaussian", interaction.depth = 5, n.trees=1000, n.minobsinnode = 10, shrinkage = 0.1)

p_gbm8 <- predict_ba_prob_gaussian_gbm1(m_gbm8, test)
s_gbm8 <- get_score_ba(p_gbm8, test$BA, u_ba, weights_ba)
s_gbm8
```




#Extremes
```{r}
threshold <- 2000
train_data$overthreshold <- ifelse(train_data$BA > threshold, 1, 0)
test$overthreshold <- ifelse(test$BA > threshold, 1, 0)

filter(test, overthreshold == 1)
```


#logistic without count
```{r}
overthreshold_nocnt <- glm(formula = overthreshold ~.-BA-CNT-pressure-lc18-mean_monthly_BA-dew_temp-lc7,family = binomial, data = train_data)

summary(overthreshold_nocnt)

predict_nocnt <- predict(overthreshold_nocnt, newdata = test, type = "response") #predicting prb that BA > threshold

test$nocnt_overthreshold <- predict_nocnt

filter(test, nocnt_overthreshold > 0.05 & CNT !=0 )
filter(test, nocnt_overthreshold > 0.05 & BA > 2000)


```

#logistic with count
```{r}
overthreshold_cnt <- glm(formula = overthreshold ~.-BA-mean_monthly_BA-lc18-altiSD-lc7, family = binomial, data = train_data)

predict_cnt <- predict(overthreshold_cnt, newdata = test, type = "response") #predicting prb that BA > threshold

test$cnt_overthreshold <- predict_cnt

filter(test, cnt_overthreshold > 0.1 & CNT !=0 )
filter(test, cnt_overthreshold > 0.1 & BA > 2000)
```





```{r}
train <- train_data %>% filter(BA <= threshold)
```


#gbm without count training on BA <= threshold
```{r}
m_gbm_nocnt <- gbm(log(BA+1) ~ .-CNT-mean_monthly_BA-overthreshold, data = train, distribution = "gaussian", interaction.depth = 6, n.trees=1000, n.minobsinnode = 10, shrinkage = 0.1)

p_gbm_nocnt <- predict_ba_prob_gaussian_gbm1(m_gbm_nocnt, test)
```


# gbm with count training on BA <= threshold
```{r}
m_gbm_cnt <- gbm(log(BA+1) ~.-mean_monthly_BA-overthreshold, data = train, distribution = "gaussian", interaction.depth = 6, n.trees=1000, n.minobsinnode = 10, shrinkage = 0.1)

p_gbm_cnt <- predict_ba_prob_gaussian_gbm1(m_gbm_cnt, test)
```

```{r}
m_gbm_cnt <- gbm(log(BA+1) ~. )
```



#vglm gpd model for BA > threshold
```{r}
library(VGAM)

modelvglm <- vglm(BA~.-BA-CNT-overthreshold-mean_monthly_BA-mean_monthly_CNT, family = gpd(threshold = threshold), link = "log", data = train_data, subset = BA > threshold)

modelvglm_cnt <-  vglm(BA~.-BA-overthreshold-mean_monthly_BA-mean_monthly_CNT, family = gpd(threshold = threshold), link = "log", data = train_data, subset = BA > threshold)



```


# computing scores

#without cnt
```{r}
new_glm <- test %>% filter(nocnt_overthreshold > 0.01) 
rows_glm <- which(test$nocnt_overthreshold > 0.01)

predictedvglm <- predict(modelvglm, untransform = TRUE, newdata = new_glm) #predict with gpd the selected rows

u_ba_threshold <- subset(u_ba, u_ba > threshold)

x = matrix(0, nrow(new_glm), length(u_ba_threshold))
for (i in 1:nrow(predictedvglm)){
  for (j in 1:length(u_ba_threshold))
    x[i,j] <- pgpd(u_ba_threshold[j], scale = predictedvglm[i,1] , shape = predictedvglm[i,2]) 
    #prob that BA <  u_ba_threshold given that BA > threshold
}

prob_threshold = matrix(0, nrow(x), length(u_ba_threshold))
for (i in 1:nrow(x)){
  prob_threshold[i,] <- x[i,] * new_glm$nocnt_overthreshold[i]
}

a <- p_gbm_nocnt
a[rows_glm, 22:28] <- a[rows_glm, 21] +prob_threshold

p1 <- a
q <- a[rows_glm,28] -1
a[rows_glm,] <- p1[rows_glm, ]- q

for (i in 1:24521){
  for(j in 1:28){
    if (a[i,j] < 0) {
      a[i,j] <- 0
    }
  }
}


score_nocnt <- get_score_ba(a, test$BA, u_ba, weights_ba)
score_nocnt
```


#score with cnt
```{r}
new_glm <- test %>% filter(cnt_overthreshold > 0.01 & CNT != 0) 
rows_glm <- which(test$cnt_overthreshold > 0.01 & test$CNT != 0)

predictedvglm <- predict(modelvglm, untransform = TRUE, newdata = new_glm) #predict with gpd the selected rows

u_ba_threshold <- subset(u_ba, u_ba > threshold)

x = matrix(0, nrow(new_glm), length(u_ba_threshold))
for (i in 1:nrow(predictedvglm)){
  for (j in 1:length(u_ba_threshold))
    x[i,j] <- pgpd(u_ba_threshold[j], scale = predictedvglm[i,1] , shape = predictedvglm[i,2]) 
    #prob that BA <  u_ba_threshold given that BA > threshold
}

prob_threshold = matrix(0, nrow(x), length(u_ba_threshold))
for (i in 1:nrow(x)){
  prob_threshold[i,] <- x[i,] * new_glm$cnt_overthreshold[i]
}

a <- p_gbm_cnt

a[rows_glm, 22:28] <- a[rows_glm, 21] +prob_threshold


p1 <- a
q <- a[rows_glm,28] -1
a[rows_glm,] <- p1[rows_glm, ]- q

for (i in 1:24521){
  for(j in 1:28){
    if (a[i,j] < 0) {
      a[i,j] <- 0
    }
  }
}

# for (i in 1:nrow(test)){
#   if (test$CNT[i] == 0){
#     for (j in 1:ncol(a))
#       a[i,j] = 1
#   }
# }

score_cnt <- get_score_ba(a, test$BA, u_ba, weights_ba)
score_cnt


```


#gbm binary
```{r}
gbm_overthreshold_cnt <- gbm(overthreshold ~.-BA-mean_monthly_BA, distribution = "bernoulli", data = train_data, n.trees = 1000)
gbm_predict_cnt <- predict(gbm_overthreshold_cnt, newdata = test, type = "response", n.trees = 1000) #predicting prb that BA > threshold

test$gbm_cnt_overthreshold <- gbm_predict_cnt

nrow(filter(test, gbm_cnt_overthreshold > 0.05))
nrow(filter(test, gbm_cnt_overthreshold > 0.05 & BA > 2000))

filter(test, cnt_overthreshold > 0.05 & BA> 2000)

predicted <- ifelse(gbm_predict_cnt > 0.05, 1, 0)
c <-table( predicted, test$gbm_cnt_overthreshold )
a <-sum(diag(c))/sum(c)
c
a

library(caret)
1-precision(c) #0.9959628
recall(c)

filter(test, gbm_cnt_overthreshold > 0.01 & BA > 2000)
filter(test, gbm_cnt_overthreshold > 0.01)

```

```{r}
gbm_overthreshold_nocnt <- gbm(overthreshold ~.-CNT-BA-mean_monthly_BA, distribution = "bernoulli", data = train_data, n.trees = 1000)
gbm_predict_nocnt <- predict(gbm_overthreshold_nocnt, newdata = test, type = "response", n.trees = 1000) #predicting prb that BA > threshold

test$gbm_nocnt_overthreshold <- gbm_predict_nocnt

nrow(filter(test, gbm_nocnt_overthreshold > 0.01))
nrow(filter(test, gbm_nocnt_overthreshold > 0.01 & BA > 2000))

predicted <- ifelse(gbm_predict_nocnt > 0.05, 1, 0)
c1 <-table(test$gbm_nocnt_overthreshold, predicted)


library(caret)
1-precision(c1) #0.9959628
recall(c1)


filter(test, overthreshold == 1)
filter(test, gbm_nocnt_overthreshold > 0.01 & BA > 2000)
filter(test, gbm_nocnt_overthreshold > 0.01)
```




#score with cnt
```{r}
new_glm_gbm <- test %>% filter(gbm_cnt_overthreshold > 0.01 & CNT != 0) 
rows_glm_gbm <- which(test$gbm_cnt_overthreshold > 0.01 & test$CNT != 0)

predictedvglm <- predict(modelvglm, untransform = TRUE, newdata = new_glm_gbm) #predict with gpd the selected rows

u_ba_threshold <- subset(u_ba, u_ba > threshold)

x = matrix(0, nrow(new_glm_gbm), length(u_ba_threshold))
for (i in 1:nrow(predictedvglm)){
  for (j in 1:length(u_ba_threshold))
    x[i,j] <- pgpd(u_ba_threshold[j], scale = predictedvglm[i,1] , shape = predictedvglm[i,2]) 
    #prob that BA <  u_ba_threshold given that BA > threshold
}

prob_threshold = matrix(0, nrow(x), length(u_ba_threshold))
for (i in 1:nrow(x)){
  prob_threshold[i,] <- x[i,] * new_glm_gbm$gbm_cnt_overthreshold[i]
}

a <- p_gbm_cnt

a[rows_glm_gbm, 22:28] <- a[rows_glm_gbm, 21] +prob_threshold


p1 <- a
q <- a[rows_glm_gbm,28] -1
a[rows_glm_gbm,] <- p1[rows_glm_gbm, ]- q

for (i in 1:24521){
  for(j in 1:28){
    if (a[i,j] < 0) {
      a[i,j] <- 0
    }
  }
}

# for (i in 1:nrow(test)){
#   if (test$CNT[i] == 0){
#     for (j in 1:ncol(a))
#       a[i,j] = 1
#   }
# }

score_cnt_gbm <- get_score_ba(a, test$BA, u_ba, weights_ba)
score_cnt_gbm


```


```{r}
new_glm <- test %>% filter(gbm_nocnt_overthreshold > 0.01) 
rows_glm <- which(test$gbm_nocnt_overthreshold > 0.01)

predictedvglm <- predict(modelvglm, untransform = TRUE, newdata = new_glm) #predict with gpd the selected rows

u_ba_threshold <- subset(u_ba, u_ba > threshold)

x = matrix(0, nrow(new_glm), length(u_ba_threshold))
for (i in 1:nrow(predictedvglm)){
  for (j in 1:length(u_ba_threshold))
    x[i,j] <- pgpd(u_ba_threshold[j], scale = predictedvglm[i,1] , shape = predictedvglm[i,2]) 
    #prob that BA <  u_ba_threshold given that BA > threshold
}

prob_threshold = matrix(0, nrow(x), length(u_ba_threshold))
for (i in 1:nrow(x)){
  prob_threshold[i,] <- x[i,] * new_glm$gbm_nocnt_overthreshold[i]
}

a <- p_gbm_nocnt
a[rows_glm, 22:28] <- a[rows_glm, 21] +prob_threshold

p1 <- a
q <- a[rows_glm,28] -1
a[rows_glm,] <- p1[rows_glm, ]- q

for (i in 1:24521){
  for(j in 1:28){
    if (a[i,j] < 0) {
      a[i,j] <- 0
    }
  }
}


score_nocnt_gbm <- get_score_ba(a, test$BA, u_ba, weights_ba)
score_nocnt_gbm
```



#Naive Bayes
```{r}
library(naivebayes)

train_data$overthresholdf <- as.factor(train_data$overthreshold)
test$overthresholdf <- as.factor(test$overthreshold)
naivebayes_nocnt <- naive_bayes(overthresholdf ~.-BA-CNT-mean_monthly_CNT-overthreshold, data = train_data, usekernel = T) 
```

```{r}
p_naivebayes <- predict(naivebayes_nocnt, test, 'prob' )
p_naivebayes

test$nocnt_naivebayes <- p_naivebayes[,2]

filter(test, nocnt_naivebayes > 0.05)
filter(test, nocnt_naivebayes > 0.05 & BA > 2000)


filter(test, overthreshold == 1)
# correctly predicted 127/382
# 61 false positive cases

```
```{r}
new <- test %>% filter(nocnt_naivebayes > 0.01) 
rows <- which(test$nocnt_naivebayes > 0.01)

predictedvglm <- predict(modelvglm, untransform = TRUE, newdata = new) #predict with gpd the selected rows

u_ba_threshold <- subset(u_ba, u_ba > threshold)

x = matrix(0, nrow(new), length(u_ba_threshold))
for (i in 1:nrow(predictedvglm)){
  for (j in 1:length(u_ba_threshold))
    x[i,j] <- pgpd(u_ba_threshold[j], scale = predictedvglm[i,1] , shape = predictedvglm[i,2]) 
    #prob that BA <  u_ba_threshold given that BA > threshold
}

prob_threshold = matrix(0, nrow(x), length(u_ba_threshold))
for (i in 1:nrow(x)){
  prob_threshold[i,] <- x[i,] * new$nocnt_naivebayes[i]
}

a <- p_gbm_nocnt
a[rows, 22:28] <- a[rows, 21] +prob_threshold

p1 <- a
q <- a[rows,28] -1
a[rows,] <- p1[rows, ]- q

for (i in 1:24521){
  for(j in 1:28){
    if (a[i,j] < 0) {
      a[i,j] <- 0
    }
  }
}


score_nocnt_bayes <- get_score_ba(a, test$BA, u_ba, weights_ba)
score_nocnt_bayes
```


```{r}
naivebayes_cnt <- naive_bayes(overthresholdf ~.-BA-mean_monthly_CNT-overthreshold, data = train_data, usekernel = T) 
p_naivebayescnt <- predict(naivebayes_cnt, test, 'prob' )
p_naivebayescnt

test$cnt_naivebayes <- p_naivebayescnt[,2]

filter(test, cnt_naivebayes > 0.05)
filter(test, cnt_naivebayes > 0.05 & BA > 2000)


filter(test, overthreshold == 1)
# correctly predicted 127/382
# 61 false positive cases

```


```{r}
new <- test %>% filter(cnt_naivebayes > 0.01) 
rows <- which(test$cnt_naivebayes > 0.01)

predictedvglm <- predict(modelvglm, untransform = TRUE, newdata = new) #predict with gpd the selected rows

u_ba_threshold <- subset(u_ba, u_ba > threshold)

x = matrix(0, nrow(new), length(u_ba_threshold))
for (i in 1:nrow(predictedvglm)){
  for (j in 1:length(u_ba_threshold))
    x[i,j] <- pgpd(u_ba_threshold[j], scale = predictedvglm[i,1] , shape = predictedvglm[i,2]) 
    #prob that BA <  u_ba_threshold given that BA > threshold
}

prob_threshold = matrix(0, nrow(x), length(u_ba_threshold))
for (i in 1:nrow(x)){
  prob_threshold[i,] <- x[i,] * new$cnt_naivebayes[i]
}

a <- p_gbm_cnt
a[rows, 22:28] <- a[rows, 21] +prob_threshold

p1 <- a
q <- a[rows,28] -1
a[rows,] <- p1[rows, ]- q

for (i in 1:24521){
  for(j in 1:28){
    if (a[i,j] < 0) {
      a[i,j] <- 0
    }
  }
}


score_cnt_bayes <- get_score_ba(a, test$BA, u_ba, weights_ba)
score_cnt_bayes





```
